# Generated by Django 3.1.4 on 2020-12-10 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('population', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(help_text='International 3 letter country code', max_length=3, primary_key=True, serialize=False)),
                ('short_code', models.CharField(help_text='International 2 letter country code', max_length=2, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('surface_area', models.PositiveIntegerField()),
                ('independence_year', models.SmallIntegerField(null=True)),
                ('population', models.PositiveBigIntegerField(default=0)),
                ('life_expectancy', models.FloatField(null=True)),
                ('GNP', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('local_name', models.CharField(max_length=50)),
                ('government', models.CharField(max_length=50)),
                ('head_of_state', models.CharField(max_length=40, null=True)),
                ('capital', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_country', to='world.city')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(choices=[('AFRICA', 'Africa'), ('ANTARCTICA', 'Antarctica'), ('ASIA', 'Asia'), ('EUROPE', 'Europe'), ('NORTH_AMERICA', 'North America'), ('OCEANIA', 'Oceania'), ('SOUTH_AMERICA', 'South America')], max_length=15)),
                ('region', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CountryLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_official', models.BooleanField()),
                ('percentage', models.FloatField()),
                ('country', models.ForeignKey(db_column='country_code', on_delete=django.db.models.deletion.CASCADE, to='world.country')),
                ('language', models.ForeignKey(db_column='language_name', on_delete=django.db.models.deletion.CASCADE, to='world.language')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='languages',
            field=models.ManyToManyField(through='world.CountryLanguage', to='world.Language'),
        ),
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='countries', to='world.region'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(db_column='country_code', on_delete=django.db.models.deletion.CASCADE, to='world.country'),
        ),
        migrations.AddField(
            model_name='city',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='world.district'),
        ),
    ]
